/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication3;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jedidiah
 */
public class personal_info extends javax.swing.JFrame {

    /**
     * Creates new form personal_info
     */
    public String[] seats;
    public int i;
    public personal_info() {
        initComponents();
    }
    public personal_info(String[] seat,int i) {
        initComponents();
        this.seats=seat;
        this.i=i;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pass_error = new javax.swing.JPanel();
        name_lab = new javax.swing.JLabel();
        last_name_lab = new javax.swing.JLabel();
        passport_lab = new javax.swing.JLabel();
        first_name_field = new javax.swing.JTextField();
        last_name_field = new javax.swing.JTextField();
        passport_field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        WarningText1 = new javax.swing.JLabel();
        WarningText2 = new javax.swing.JLabel();
        WarningText3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        From_op = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        To_op = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        departure_label = new javax.swing.JLabel();
        departure_label1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Book_btn = new javax.swing.JButton();
        Cancel_Book_btn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        FlightNoHeader6 = new javax.swing.JLabel();
        FlightNoHeader7 = new javax.swing.JLabel();
        MainLogo4 = new javax.swing.JLabel();
        MainLogo9 = new javax.swing.JLabel();
        MainLogo10 = new javax.swing.JLabel();
        MainLogo6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pass_error.setBackground(new java.awt.Color(0, 240, 240,80));

        name_lab.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        name_lab.setText("First Name");

        last_name_lab.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        last_name_lab.setText("Last Name");

        passport_lab.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        passport_lab.setText("Passport No");

        first_name_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_name_fieldActionPerformed(evt);
            }
        });

        passport_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passport_fieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel2.setText("Personal info");

        WarningText1.setForeground(new java.awt.Color(255, 0, 0));

        WarningText2.setForeground(new java.awt.Color(255, 0, 0));

        WarningText3.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pass_errorLayout = new javax.swing.GroupLayout(pass_error);
        pass_error.setLayout(pass_errorLayout);
        pass_errorLayout.setHorizontalGroup(
            pass_errorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pass_errorLayout.createSequentialGroup()
                .addGroup(pass_errorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pass_errorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pass_errorLayout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addGroup(pass_errorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pass_errorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(last_name_lab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(name_lab, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                                .addGroup(pass_errorLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(pass_errorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(last_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(WarningText2)
                                        .addComponent(WarningText3)
                                        .addComponent(passport_field, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(passport_lab, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pass_errorLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(pass_errorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(first_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(WarningText1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pass_errorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        pass_errorLayout.setVerticalGroup(
            pass_errorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pass_errorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name_lab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WarningText1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(first_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(last_name_lab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WarningText2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(last_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(passport_lab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WarningText3)
                .addGap(1, 1, 1)
                .addComponent(passport_field, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(pass_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 310, -1));

        jPanel1.setBackground(new java.awt.Color(0,240, 240,80));

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 0, 20)); // NOI18N
        jLabel3.setText("From");

        From_op.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adiss_Abeba", "Bahirdar", "Hawassa", "Mekelle", "Gimma", "Melborne", "Newyork", "Moscow", "Londen", "Norway", "Rio-Degenerio", "Mombassa", "Frankfurt", "Tokyo", "Bejing" }));
        From_op.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                From_opActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 0, 20)); // NOI18N
        jLabel4.setText("To");

        To_op.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adiss_Abeba", "Bahirdar", "Hawassa", "Mekelle", "Gimma", "Melborne", "Newyork", "Moscow", "Londen", "Norway", "Rio-Degenerio", "Mombassa", "Frankfurt", "Tokyo", "Bejing" }));
        To_op.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                To_opActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel5.setText("Departure Date");

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel6.setText("Departure Time");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(From_op, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 96, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(departure_label1)
                            .addComponent(departure_label))))
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(To_op, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(From_op, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(To_op, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(departure_label))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departure_label1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 430, 110));

        jSeparator1.setBackground(new java.awt.Color(102, 102, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 51, 51));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 40, 400));

        Book_btn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        Book_btn.setText("Next");
        Book_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Book_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 480, -1, -1));

        Cancel_Book_btn1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        Cancel_Book_btn1.setText("Cancel");
        Cancel_Book_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_Book_btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel_Book_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication3/photo_171@14-05-2020_20-10-56.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 840, 440));

        Header.setBackground(new java.awt.Color(51, 255, 51));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FlightNoHeader6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FlightNoHeader6.setForeground(new java.awt.Color(0, 102, 0));
        FlightNoHeader6.setText("SEATS");
        Header.add(FlightNoHeader6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 60, 30));

        FlightNoHeader7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FlightNoHeader7.setForeground(new java.awt.Color(255, 255, 255));
        FlightNoHeader7.setText("PASSENGER");
        Header.add(FlightNoHeader7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 90, 30));

        MainLogo4.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        MainLogo4.setForeground(new java.awt.Color(255, 255, 255));
        MainLogo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication3/l1.png"))); // NOI18N
        Header.add(MainLogo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 210, 110));

        MainLogo9.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        MainLogo9.setForeground(new java.awt.Color(255, 255, 255));
        MainLogo9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication3/circle - Copy.png"))); // NOI18N
        Header.add(MainLogo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 20, 20));

        MainLogo10.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        MainLogo10.setForeground(new java.awt.Color(255, 255, 255));
        MainLogo10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication3/circleDisable.png"))); // NOI18N
        Header.add(MainLogo10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 20, 20));

        MainLogo6.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        MainLogo6.setForeground(new java.awt.Color(255, 255, 255));
        MainLogo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication3/lines.png"))); // NOI18N
        Header.add(MainLogo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 130, 20));

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Book_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_btnActionPerformed
        // TODO add your handling code here:
        
        if (first_name_field.getText().isEmpty() && last_name_field.getText().isEmpty() && passport_field.getText().isEmpty()) {
            WarningText1.setText("* First Name is Required");
            WarningText2.setText("* Last Name is Required");
            WarningText3.setText("* Passport No. is Required");
            
        } else if (first_name_field.getText().isEmpty() && last_name_field.getText().isEmpty()) {
            WarningText1.setText("* First Name is Required");
            WarningText2.setText("* Last Name is Required");
            WarningText3.setText("");
        } else if (first_name_field.getText().isEmpty() && passport_field.getText().isEmpty()) {
            WarningText1.setText("* First Name is Required");
            WarningText2.setText("");
            WarningText3.setText("* Passport No. is Required");
        } else if (last_name_field.getText().isEmpty() && passport_field.getText().isEmpty()) {
            WarningText1.setText("");
            WarningText2.setText("* Last Name is Required");
            WarningText3.setText("* Passport No. is Required");
        } else if (first_name_field.getText().isEmpty()) {
            WarningText1.setText("* First Name is Required");
            WarningText2.setText("");
            WarningText3.setText("");
        } else if (last_name_field.getText().isEmpty()) {
            WarningText1.setText("");
            WarningText2.setText("* Last Name is Required");
            WarningText3.setText("");
        } else if (passport_field.getText().isEmpty()) {
            WarningText1.setText("");
            WarningText2.setText("");
            WarningText3.setText("* Passport No. is Required");
        }else {
            String firstName = first_name_field.getText();
            String lastName = last_name_field.getText();
            String passportNo = passport_field.getText();
            
        
            Seat_booking sb=new Seat_booking(seats,i,firstName,lastName,passportNo,(String)From_op.getSelectedItem(),(String)To_op.getSelectedItem(),departure_label.getText(),departure_label1.getText());
            sb.setVisible(true);
            this.setVisible(false);
            
        }
        
        
        
        
    }//GEN-LAST:event_Book_btnActionPerformed

    private void Cancel_Book_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_Book_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cancel_Book_btn1ActionPerformed

    private void passport_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passport_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passport_fieldActionPerformed

    private void From_opActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_From_opActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_From_opActionPerformed

    private void To_opActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_To_opActionPerformed
        // TODO add your handling code here
        Random r =new Random();
       String[] nam={"5:27 PM 8/27/2021-7:27 PM 8/27/2021",
                     "7:00 PM 8/3/2021-8:45 PM 8/3/2021",
                     "1:00 AM 1/2/2021-4:30 AM 1/2/2021",
                    "5:30 PM 8/27/2021-7:27 PM 9/27/2021",
                     "11:00 AM 12/7/2021-12:30 PM 12/7/2021"};
       int x=r.nextInt()%5;
       x= x < 0 ? -x : x; 
       System.out.println(nam[x]);
        String[] s1=nam[x].split("-");
       departure_label.setText(s1[0]);
       departure_label1.setText(s1[1]);
    }//GEN-LAST:event_To_opActionPerformed

    private void first_name_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_name_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_first_name_fieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(personal_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(personal_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(personal_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(personal_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new personal_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Book_btn;
    private javax.swing.JButton Cancel_Book_btn1;
    private javax.swing.JLabel FlightNoHeader6;
    private javax.swing.JLabel FlightNoHeader7;
    private javax.swing.JComboBox<String> From_op;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel MainLogo10;
    private javax.swing.JLabel MainLogo4;
    private javax.swing.JLabel MainLogo6;
    private javax.swing.JLabel MainLogo9;
    private javax.swing.JComboBox<String> To_op;
    private javax.swing.JLabel WarningText1;
    private javax.swing.JLabel WarningText2;
    private javax.swing.JLabel WarningText3;
    private javax.swing.JLabel departure_label;
    private javax.swing.JLabel departure_label1;
    private javax.swing.JTextField first_name_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField last_name_field;
    private javax.swing.JLabel last_name_lab;
    private javax.swing.JLabel name_lab;
    private javax.swing.JPanel pass_error;
    private javax.swing.JTextField passport_field;
    private javax.swing.JLabel passport_lab;
    // End of variables declaration//GEN-END:variables
}
